language: python
python: "2.7"

sudo: enabled
dist: trusty

install:
  - "pip install -r src/requirements.txt"
  
script:
  - "ls"

deploy:
  provider: s3
  access_key_id: "access_key_id"
  secret_access_key: "secret_access_key"
  bucket: "alexa-christchurchmayfairassistant"
  skip_cleanup: true
  region: eu-west-1
